<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select - Alasan Resubmission</name>
   <tag></tag>
   <elementGuidId>ab701082-698c-4355-a6f3-fc95c47612b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c62-28</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-resubmission-dialog/form/section/mat-form-field/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa4c026d-9b7d-47dd-82cd-04f2a77950e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c62-28</value>
      <webElementGuid>586580f1-b17b-4189-a333-bf9d12e3d97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose OneChoose One</value>
      <webElementGuid>c12f84ab-8caa-4e0b-bb68-496f74401365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-select[@formcontrolname=&quot;reason&quot;]</value>
      <webElementGuid>00059bb3-8c14-4c05-89c6-9e13a2be322e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-resubmission-dialog/form/section/mat-form-field/div/div/div</value>
      <webElementGuid>122b88c7-216b-4730-a978-f2fcadc6381c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alasan'])[1]/following::div[3]</value>
      <webElementGuid>efb6c698-069e-46c4-b341-55e6d2f1f4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih alasan mengapa calon peminjam perlu untuk mengirim PBB mereka.'])[1]/following::div[3]</value>
      <webElementGuid>f3c46aeb-79c9-493c-8eec-a60229d24125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field/div/div/div</value>
      <webElementGuid>f42f3c74-d0cb-45a1-85bd-d648be44b21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Choose OneChoose One' or . = 'Choose OneChoose One')]</value>
      <webElementGuid>96c846a4-f337-46b6-8a59-292514020dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
