<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video - Preview Ambil Gambar</name>
   <tag></tag>
   <elementGuidId>9481dc04-63c8-4311-beda-6573f1c5bf44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='video']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>1914a48d-c9af-4db3-9d9d-4494f7383ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>237e2605-b6ff-4123-b13d-c508734248b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>560</value>
      <webElementGuid>93d73f85-f89a-4e62-916d-47572891040a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>d1c69b95-4ca9-4e40-9411-824b351c98a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto ng-star-inserted</value>
      <webElementGuid>8c863a3d-b6d8-47eb-8dd9-cf6d9a742d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;preview-container&quot;]/*[@id=&quot;video&quot;]</value>
      <webElementGuid>4f1c1ec2-4818-41ce-8f1e-29b9f2953ae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='video']</value>
      <webElementGuid>f321608a-f4fb-4070-98a9-4063ab886479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>9aedcdb5-6dca-4c43-9dd7-700a6228ef21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'video']</value>
      <webElementGuid>8785085e-a885-42d6-acae-932204007663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
