<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Fire Insurance Fee</name>
   <tag></tag>
   <elementGuidId>dd4851c7-3895-4dd9-aa62-c4acb6a99849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;fire_insurance_fee&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='fire_insurance_fee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>809211ff-a03a-4ab6-a41e-e722e8877911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b12e1f86-ed2b-4708-bcca-9d22bbba4e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fire_insurance_fee</value>
      <webElementGuid>12535f9c-6269-46c6-8faf-9abd2dfdf5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fire_insurance_fee</value>
      <webElementGuid>1a7b8981-d758-4afc-8e97-cd78488528e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>fb39080c-7ff3-43f3-8bdb-439711d74cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>732d3bce-ca4a-4bcf-9a2a-b4dce0426bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-tns-c76-0 ng-star-inserted&quot;]/div[@class=&quot;main-container ng-tns-c76-0&quot;]/div[@class=&quot;padding-32-32-32-32 ng-tns-c76-0 padding-left&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;shadow card-ffffff-0 padding-32-32-32-32 wrapper&quot;]/lancar-tabs[1]/lancar-tab[1]/div[1]/add-offer-letter-form[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;ng-pristine ng-touched ng-valid&quot;]/div[@class=&quot;row mb-24&quot;]/div[@class=&quot;col-6&quot;]/lancar-input[1]/div[@class=&quot;input-wrapper valid&quot;]/input[@class=&quot;ng-pristine ng-touched ng-valid&quot;]</value>
      <webElementGuid>8204b582-3ebf-4df1-9df1-8102d33fc917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='fire_insurance_fee']</value>
      <webElementGuid>88a0e0c5-e182-448c-90c4-0b3c042e2b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lancar-input/div/input</value>
      <webElementGuid>8a8f8b90-bbba-4740-a581-785862eb01bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fire_insurance_fee' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>79b2a7e1-a050-4af1-bbe2-2c4e207b557c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
