<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Advance Penalty Rate</name>
   <tag></tag>
   <elementGuidId>2b180bd1-b095-48bf-a687-03904c7588e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='advance_penalty_rate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;advance_penalty_rate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>287659a5-5223-4d55-8d5b-7b58881aa913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bc54afc-101b-4ce4-b065-0c28ebb55a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advance_penalty_rate</value>
      <webElementGuid>d41cba7f-058d-4e53-9821-5ef67a45a2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>advance_penalty_rate</value>
      <webElementGuid>705368cd-ebdc-4354-af15-c970b5a2d651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>8b492623-606b-4664-9d96-86db640e0952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>c23b55f3-ad56-451e-bb41-8f371bf7dcbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname=&quot;advance_penalty_rate&quot;]</value>
      <webElementGuid>33196b1d-e531-42a4-9cf1-dc7fb4fd9dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='advance_penalty_rate']</value>
      <webElementGuid>05fa727c-714b-4bef-8622-a6efd7d29f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/lancar-input/div/input</value>
      <webElementGuid>97de328d-d4ba-46e5-a9b3-9d0a7aea9ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'advance_penalty_rate' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>a9a412b8-6b03-4ddd-a345-daec1a4574ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
