<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Provision Fee Amount</name>
   <tag></tag>
   <elementGuidId>e5bc8b7d-d022-4fd3-a8f8-480ba4362a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='provision_fee_amount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;provision_fee_amount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0da1931c-c5d2-4393-a29b-0c778e4d774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cb087bd-3627-4d48-afd9-a462025cbf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provision_fee_amount</value>
      <webElementGuid>993d7dd1-f8f2-432a-9b9e-756cef1699a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>provision_fee_amount</value>
      <webElementGuid>afc1ea89-cb87-42d1-b843-c01e9d412e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>3ea86d39-c857-4e7c-83da-872b89208c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>04a5a85e-8982-43fa-9e64-ae85721dc3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname=&quot;provision_fee_amount&quot;]</value>
      <webElementGuid>daf00d3f-b23a-45ea-8072-762921da1f94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='provision_fee_amount']</value>
      <webElementGuid>6a239485-9c52-4a87-94d4-fa68282b99be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/lancar-input/div/input</value>
      <webElementGuid>95ecbaab-70a9-4cdd-acaa-cb8ebff660da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'provision_fee_amount' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>890bd446-3c56-471c-9838-067206b35257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
