<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Logout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f132e7e2-f4fa-41b8-a5ce-c40b0f81acb8</testSuiteGuid>
   <testCaseLink>
      <guid>682f07a4-9d54-4957-aef1-4b9de9c74324</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Danamas/Android/Borrower/Login/Login with incorrect password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df61274b-7feb-4db8-81d4-36679c1d637a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d35a39e4-6f78-4a42-a1eb-058965feaa4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66dc59b7-ace6-48b0-8c16-7be2f7021ef8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Danamas/Android/Borrower/Login/Login with password less than 6 characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f41f85-618c-44c8-b99e-863d2470c756</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>486e27fa-8762-4277-bd5c-dd16889bbec4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Danamas/Android/Borrower/Login/Login with phone number less than 8 characters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>045e8aae-336a-44bb-b6be-00548f3f1b4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Danamas/Android/Borrower/Login/Login with incorrect phone number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28ba4968-942c-41a9-81e4-ce6f99f94783</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d4fee36d-2534-4b65-8694-d90bb7e79c25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Danamas/Android/Borrower/Login/Login to verified user then logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c65ba76-24c8-478c-a2dc-520032dc062b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7f34809-28d3-4381-a72f-5450eb5ae934</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
