<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>agent_profil</name>
   <tag></tag>
   <elementGuidId>f8fb7d98-726b-49b7-ab6c-0da122bdcafe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.mb-2.max-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/ng-component/div/div[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>be7723b2-c1bc-48ac-a275-a55e0530ee01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 max-line</value>
      <webElementGuid>994e6a8d-ce7b-4e15-b16f-a7f56899115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> muhammad yusuf </value>
      <webElementGuid>2f754816-875b-4657-9757-5e92fe8552c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ng-trigger ng-trigger-routerAnimation&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;profile-header&quot;]/div[@class=&quot;header-right&quot;]/div[@class=&quot;user-info ng-star-inserted&quot;]/h4[@class=&quot;mb-2 max-line&quot;]</value>
      <webElementGuid>985608a7-5075-480b-ab17-3fec90626aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/ng-component/div/div[2]/div/h4</value>
      <webElementGuid>85df192a-47c1-4265-9e53-ecb9db911832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[1]/following::h4[1]</value>
      <webElementGuid>c64dc559-fdf5-4836-ab79-43520f0d0284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/preceding::h4[1]</value>
      <webElementGuid>6ff4d18d-eefc-4541-8754-2f21e891ee61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pribadi'])[1]/preceding::h4[1]</value>
      <webElementGuid>0c14ed5b-fe16-49d2-8901-191d2bb876de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>5c787f75-2b76-462f-86bf-814b94bb4d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' muhammad yusuf ' or . = ' muhammad yusuf ')]</value>
      <webElementGuid>134cd037-289f-4ab1-a82c-568169fbf44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
