<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Meminta Kode Rahasia</name>
   <tag></tag>
   <elementGuidId>318308ab-f3b1-4248-986e-02bc5a76b631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.btn-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/app-card/div/div[2]/div/form/app-form-group[3]/div/div/div/app-button/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>859d4318-7330-400b-ba8b-39d7d50d6fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-md</value>
      <webElementGuid>a64cc590-91ac-4dd1-9de7-84737a222b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Meminta Kode Rahasia </value>
      <webElementGuid>16076c50-f708-4a84-a3bf-eef2e46a826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/app-card[@class=&quot;ng-tns-c79-11 ng-star-inserted&quot;]/div[@class=&quot;card app-card ng-tns-c79-11&quot;]/div[@class=&quot;ng-tns-c79-11 ng-trigger ng-trigger-expandCollapse&quot;]/div[@class=&quot;card-body ng-tns-c79-11&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-tns-c79-11 ng-star-inserted ng-touched&quot;]/app-form-group[3]/div[@class=&quot;form-group row mb-4&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/div[@class=&quot;d-grid&quot;]/app-button[1]/button[@class=&quot;btn btn-primary btn-md&quot;]</value>
      <webElementGuid>6f548c75-de5c-4098-993e-d8a26ffb33ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/app-card/div/div[2]/div/form/app-form-group[3]/div/div/div/app-button/button</value>
      <webElementGuid>fb919888-b4d3-4e52-ae3b-13f58daadea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data tidak boleh kosong'])[1]/following::button[1]</value>
      <webElementGuid>3687ae2a-0cf3-42fc-91fc-8cb0abbd4f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP'])[1]/following::button[1]</value>
      <webElementGuid>ca8f3e84-e9be-4073-a0e1-fb8bb3a390d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>42d00fd8-0890-4ac2-af07-a254e1fde4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Meminta Kode Rahasia ' or . = ' Meminta Kode Rahasia ')]</value>
      <webElementGuid>8a47bea9-8f16-4d7f-95af-164394741fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
