<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Advance Penalty Rate</name>
   <tag></tag>
   <elementGuidId>41e6377f-1124-40fc-90f0-271e697ca085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;advance_penalty_rate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='advance_penalty_rate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c692d142-b0a1-424b-9c14-d8236eaedd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19cd4eac-48ea-4037-93ee-0e74648800f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advance_penalty_rate</value>
      <webElementGuid>dfdd17b2-a4f0-4572-bdfa-0d005788b4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>advance_penalty_rate</value>
      <webElementGuid>2edc023c-3451-44cd-bea4-deeaa8ac2a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>3563225e-c0c0-457e-8187-3a9a7dcca16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>cc788e0d-5e4d-4d4c-917f-1d7a765452c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname=&quot;advance_penalty_rate&quot;]</value>
      <webElementGuid>2a40eb7e-d327-495b-b60c-bcac1f81038f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='advance_penalty_rate']</value>
      <webElementGuid>bdbcc21e-54b6-432e-89d4-770f7ae1368e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/lancar-input/div/input</value>
      <webElementGuid>e0f79ef3-9522-4fdd-9e22-07677f21af1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'advance_penalty_rate' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>2921d2b5-1d85-48ef-869d-2ba25f387b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
