<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select - Tipe Partner</name>
   <tag></tag>
   <elementGuidId>d0a0db98-70a0-4e83-9b0e-df9005056db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname = 'type']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87dbbeaa-9005-4f4a-b436-166523432182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>faf21e73-7eaf-403e-9a3a-a14d149abb21</webElementGuid>
   </webElementProperties>
</WebElementEntity>
