<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Provision</name>
   <tag></tag>
   <elementGuidId>cf80c62a-0888-4fc2-888d-c37ca63e1ecc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;provision_fee_rate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='provision_fee_rate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1371dbe7-0663-4c88-ba5c-294630da92b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e60bf092-c1aa-4830-9325-d1088abecd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>provision_fee_rate</value>
      <webElementGuid>eb8c3f80-326a-44a9-b74f-7c4f8e32d0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>provision_fee_rate</value>
      <webElementGuid>627cccab-24dc-4a85-9daa-289c9c516cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>f67553bf-61eb-4b26-8a67-7dba29896357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>78963d86-2db0-4996-85a6-d216f8664b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-tns-c76-0 ng-star-inserted&quot;]/div[@class=&quot;main-container ng-tns-c76-0&quot;]/div[@class=&quot;padding-32-32-32-32 ng-tns-c76-0 padding-left&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;shadow card-ffffff-0 padding-32-32-32-32 wrapper&quot;]/lancar-tabs[1]/lancar-tab[1]/div[1]/add-offer-letter-form[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;ng-pristine ng-touched ng-valid&quot;]/div[@class=&quot;row mb-24&quot;]/div[@class=&quot;col-6&quot;]/lancar-input[1]/div[@class=&quot;input-wrapper valid&quot;]/input[@class=&quot;ng-pristine ng-touched ng-valid&quot;]</value>
      <webElementGuid>5002e142-31b7-47ef-a3ac-f15d8b179a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='provision_fee_rate']</value>
      <webElementGuid>357c4d79-5e3f-4756-92c0-a485d7e86399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/lancar-input/div/input</value>
      <webElementGuid>3a4e97c2-c953-4feb-baa6-cc40a480aeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'provision_fee_rate' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>268ab4af-700d-48ad-a6b2-0d71f0f5465c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
