<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Late Penalty Fee</name>
   <tag></tag>
   <elementGuidId>09482dad-2d44-4f4a-a656-092a03da484d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;penalty_rate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='penalty_rate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0c1f919-85f9-42e2-accc-f95064d19c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9a0ab12-5c54-4473-8d6e-a8f0ba932b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>penalty_rate</value>
      <webElementGuid>bc343332-b1b1-43ff-a6a5-f776df4f0fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>penalty_rate</value>
      <webElementGuid>d6b76169-77aa-4644-99d5-84446f023faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>80f66674-efe5-4522-8617-60f1b6030031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>2e92db96-9f0e-4db4-96ce-5a42b0d7dc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-tns-c76-0 ng-star-inserted&quot;]/div[@class=&quot;main-container ng-tns-c76-0&quot;]/div[@class=&quot;padding-32-32-32-32 ng-tns-c76-0 padding-left&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;shadow card-ffffff-0 padding-32-32-32-32 wrapper&quot;]/lancar-tabs[1]/lancar-tab[1]/div[1]/add-offer-letter-form[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;ng-pristine ng-touched ng-valid&quot;]/div[@class=&quot;row mb-24&quot;]/div[@class=&quot;col-6&quot;]/lancar-input[1]/div[@class=&quot;input-wrapper valid&quot;]/input[@class=&quot;ng-pristine ng-touched ng-valid&quot;]</value>
      <webElementGuid>aa612fc7-2533-49ca-9813-057573f3c6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='penalty_rate']</value>
      <webElementGuid>aadf0d0c-7b2a-46b8-a3ce-d904d84c6de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/lancar-input/div/input</value>
      <webElementGuid>af613805-9112-428b-8845-a27351573bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'penalty_rate' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>674cf982-a15d-4823-b0fe-00dbcdee9ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
