<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Life Insurance Fee</name>
   <tag></tag>
   <elementGuidId>793d1c2a-42df-41c5-8525-775dab052f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;life_insurance_fee&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='life_insurance_fee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fbe26bf-1ace-4e7a-bb69-5255d2c35479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>716a6f6d-5b42-465e-b1d3-4889b9776976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>life_insurance_fee</value>
      <webElementGuid>abe2dbc0-d5cb-450d-b99f-39d8c107bdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>life_insurance_fee</value>
      <webElementGuid>4b1834ab-98a9-4df2-9719-7d6997c35b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Besaran Bunga</value>
      <webElementGuid>9a617a47-e7a0-4d6f-b6e7-c22164cd69ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-touched ng-valid</value>
      <webElementGuid>991753c6-53da-4004-9dc1-7d9ed170847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-tns-c76-0 ng-star-inserted&quot;]/div[@class=&quot;main-container ng-tns-c76-0&quot;]/div[@class=&quot;padding-32-32-32-32 ng-tns-c76-0 padding-left&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;shadow card-ffffff-0 padding-32-32-32-32 wrapper&quot;]/lancar-tabs[1]/lancar-tab[1]/div[1]/add-offer-letter-form[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;ng-pristine ng-touched ng-valid&quot;]/div[@class=&quot;row mb-24&quot;]/div[@class=&quot;col-6&quot;]/lancar-input[1]/div[@class=&quot;input-wrapper valid&quot;]/input[@class=&quot;ng-pristine ng-touched ng-valid&quot;]</value>
      <webElementGuid>abba2bf0-a4df-4d55-adb2-64f8f5995a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='life_insurance_fee']</value>
      <webElementGuid>e27c39a0-8145-4388-9e0c-17fa5490cb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div/lancar-input/div/input</value>
      <webElementGuid>2158ec7d-5078-46d2-acf4-0881fc9c6475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'life_insurance_fee' and @placeholder = 'Masukkan Besaran Bunga']</value>
      <webElementGuid>f5aae7b2-98f5-43f8-845e-f156a2fa1141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
