<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Close Password Popup</name>
   <tag></tag>
   <elementGuidId>771451cf-59cb-43dc-9ea0-86274ab86629</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>aside > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-new-password/div/aside/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>164da40f-8256-4d0b-834b-0ea9dea77d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../../assets/icons/close-icon-black.svg</value>
      <webElementGuid>77cfb2cc-969b-4be7-ae53-3d31f4bc561a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-new-password//aside/img</value>
      <webElementGuid>ec8de1f3-cbfa-4541-9200-8febcca1c297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-new-password/div/aside/img</value>
      <webElementGuid>31581a8b-ebc8-4fb1-8da1-2412e719ae48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/img</value>
      <webElementGuid>fddb33e7-af8f-4260-9b27-bc19ab00ca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../../../assets/icons/close-icon-black.svg']</value>
      <webElementGuid>2d3236a5-20f7-4a68-95e8-789a7ceae78a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
