<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Nilai Minimum Properti</name>
   <tag></tag>
   <elementGuidId>1ae8ff93-bfb8-4819-9eb1-21d59bb782ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id2']/h2/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2041ada6-9ce6-4653-ba8f-51db68f43026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>349a4ff7-c578-4d73-b01a-2d32d16e1f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]</value>
      <webElementGuid>9d0b86bd-6bbf-403b-aa4d-86d46df3108b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>2acd723b-9788-4b98-8c68-75238474c656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2500</value>
      <webElementGuid>582ddbf4-da32-474c-98f5-712888621d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-editable-input-ivt[1]//input</value>
      <webElementGuid>f731f30f-f96d-4c0b-817a-99dd28f6fdbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id2']/h2/input</value>
      <webElementGuid>fdc28ef5-c490-4bdb-b774-8a9f4af0c70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>47a3087c-6000-4f1b-ae58-b7be843b4f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
