<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Nilai Pinjaman</name>
   <tag></tag>
   <elementGuidId>c097c4d8-f2f8-4930-9495-a12014106e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id1 > h2 > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id1']/h2/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>528ad913-6961-4638-a5aa-ecefdc339e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>597fbcec-d9d8-4292-9f49-688b34b5a728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]</value>
      <webElementGuid>ef26f477-252d-4931-b9f6-09fb5f15d2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5c3814d3-6c26-4c2d-9269-ad6e6d625f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>7733a7db-9553-4240-9a1a-f2889435eb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-editable-input-ivt[2]//input</value>
      <webElementGuid>62f47b61-34d1-4435-9151-50aee733c11b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id1']/h2/input</value>
      <webElementGuid>d4e9f1a4-22dd-4d2a-b942-07ed85fe6127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-editable-input-ivt[2]/div/h2/input</value>
      <webElementGuid>483b2a9a-a36c-4b3b-b940-71d4543cf6fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
