<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select - Nama Cabang</name>
   <tag></tag>
   <elementGuidId>a25a5b7e-e481-4ed6-bbdd-5b5cf2dd356d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.dropdown-toggle.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b488ed6-bca1-4416-a04e-f13ab57e9463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a1b1699-a4d2-4b82-a45f-a0e2816bdece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>branch_name</value>
      <webElementGuid>cec50527-3985-4f32-b89e-79359f193eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Cabang</value>
      <webElementGuid>80e4109d-77e6-4c4b-9fcd-50ba2f9aa145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cbf10089-5ddf-491d-9199-c034c03f907d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f124a2c1-def8-4c31-b6e4-dd5643a7d1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-dashboard[@class=&quot;ng-tns-c84-0 ng-star-inserted&quot;]/div[@class=&quot;main-container ng-tns-c84-0&quot;]/div[@class=&quot;padding-32-32-32-32 ng-tns-c84-0 padding-left&quot;]/app-request[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-ffffff-0 shadow padding-32-40-32-16&quot;]/form[@class=&quot;mt-16 ng-pristine ng-valid ng-touched&quot;]/div[@class=&quot;d-flex mt-32&quot;]/div[@class=&quot;mr-24 ng-star-inserted show dropdown&quot;]/lancar-input[1]/div[@class=&quot;input-wrapper focus&quot;]/input[@class=&quot;dropdown-toggle ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>fa971f20-f009-4aa4-8b34-d30796c2dba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>fe8bb1de-e3bd-4113-93e4-2bd6caba27fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/lancar-input/div/input</value>
      <webElementGuid>49e385c4-3f3c-4959-97b6-09c3818f0fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nama Cabang']</value>
      <webElementGuid>571d83fe-ddb5-4012-96f3-edc0f7b16c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
