<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buat Akun</name>
   <tag></tag>
   <elementGuidId>67bfc13f-779c-42d0-964f-5e8532af6551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-md.btn-outline-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//footer[@id='footer']/div/div/app-button[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d61e8282-5f78-4a69-a881-765823ffb3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-outline-primary</value>
      <webElementGuid>33940038-5e21-48e5-b4c8-695e08af4702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Buat Akun </value>
      <webElementGuid>4c0a2113-50ca-481b-bf8f-fa5069c7fa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/div[@class=&quot;py-3 px-3&quot;]/div[@class=&quot;d-grid gap-2 ng-star-inserted&quot;]/app-button[2]/button[@class=&quot;btn btn-md btn-outline-primary&quot;]</value>
      <webElementGuid>22ddcdfa-89ea-4d7c-b709-5ed67161c830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div/div/app-button[2]/button</value>
      <webElementGuid>9ecd69c4-4396-4bd1-9bee-27143213470b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::button[1]</value>
      <webElementGuid>74f4d968-d8b8-4ffd-b2f7-c45c116f6ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tempat dimana agen dan peminjam bertemu'])[1]/following::button[2]</value>
      <webElementGuid>cb911304-dabf-436b-ae7e-f4e826cfb76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Akun']/parent::*</value>
      <webElementGuid>93a61ac3-5906-4759-85e6-e61edc26650a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button[2]/button</value>
      <webElementGuid>5f02d4e1-94d6-4ec7-8340-0ce395e1aba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Buat Akun ' or . = ' Buat Akun ')]</value>
      <webElementGuid>5a65009c-2668-4897-9a76-2b145a321bfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
