<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ketikulangpassword</name>
   <tag></tag>
   <elementGuidId>1efbbaf8-f69f-451a-a7bf-084133b0e537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='integer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-input.ng-untouched.ng-pristine.ng-invalid > div.input-group.app-input-group.ng-star-inserted > input.form-control</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@auto_name=&quot;reTypePassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>836f7e19-604c-48f2-bb7f-cf15cc7955af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@auto_name=&quot;reTypePassword&quot;]</value>
      <webElementGuid>df12421e-5a2e-4958-88b1-266de48c7350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='integer']</value>
      <webElementGuid>8472ba8f-8f97-4ad9-bfc4-9375dd863917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/app-card/div/div[2]/div/form/app-form-group[3]/div/div/app-input/div/input</value>
      <webElementGuid>eb5276c7-d5d3-4458-a152-9eca50b60ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-group[3]/div/div/app-input/div/input</value>
      <webElementGuid>343eb171-91b3-41f4-b7eb-69b84fd0a699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan NIK Anda' and @type = 'integer']</value>
      <webElementGuid>1ea63827-fc28-463b-870c-bb0a346ccf21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
