<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor rekening</name>
   <tag></tag>
   <elementGuidId>885bd9c3-dab6-4dec-827c-178bfccb6e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@auto_name = 'account_number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='integer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98dd5c7d-9165-4cb7-98dd-68ea7acbd8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[contains(@class,&quot;form-control is-invalid&quot;)])[2]</value>
      <webElementGuid>39fa1bc4-da8f-498d-96f5-2c0c40e54e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>account_number</value>
      <webElementGuid>5257b039-a508-4f0e-b36f-4230026b8b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='integer']</value>
      <webElementGuid>c11f4d11-e297-4372-b3e5-fb30b7de1c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/app-card/div/div[2]/div/form/app-form-group[3]/div/div/app-input/div/input</value>
      <webElementGuid>64a670d9-23b0-474d-a146-987d98dd2ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-group[3]/div/div/app-input/div/input</value>
      <webElementGuid>d75cb6e9-47e8-4b0a-a444-e0b0758e873a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Masukkan nomor rekening Anda' and @type = 'integer']</value>
      <webElementGuid>656b664e-7d6e-4a6f-8e19-9f1982bb0d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
