<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Jenis Kelamin</name>
   <tag></tag>
   <elementGuidId>79cc57a9-26b1-43aa-8324-398bbc18233d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/app-card/div/div[2]/div/form/app-form-group[6]/div/div/app-select/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-select.app-drop-down-select.ng-pristine.ng-invalid.ng-star-inserted.is-invalid.ng-touched</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>24033a57-7203-45c7-aff1-225e0b5b3577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select app-drop-down-select ng-pristine ng-invalid ng-star-inserted is-invalid ng-touched</value>
      <webElementGuid>54cd652b-966b-4ccf-85f9-b5bb7a49fa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>3e46e0b1-c151-4dd7-bb30-9dbc95207a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Jenis Kelamin  Laki-laki  Perempuan </value>
      <webElementGuid>e854bdc4-ea99-4c03-bfcf-37f82fd3e0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/app-card[@class=&quot;ng-tns-c81-3 ng-star-inserted&quot;]/div[@class=&quot;card app-card ng-tns-c81-3&quot;]/div[@class=&quot;ng-tns-c81-3 ng-trigger ng-trigger-expandCollapse&quot;]/div[@class=&quot;card-body ng-tns-c81-3&quot;]/form[@class=&quot;ng-invalid ng-tns-c81-3 ng-star-inserted ng-touched ng-dirty&quot;]/app-form-group[6]/div[@class=&quot;form-group row mb-4 required&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/app-select[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/select[@class=&quot;form-select app-drop-down-select ng-pristine ng-invalid ng-star-inserted is-invalid ng-touched&quot;]</value>
      <webElementGuid>748747d6-a9a5-4eb6-b14b-5edcfbdd4d52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/app-card/div/div[2]/div/form/app-form-group[6]/div/div/app-select/select</value>
      <webElementGuid>d923d19f-4a7b-405c-96dd-5cd032c446d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih jenis kelamin'])[1]/following::select[1]</value>
      <webElementGuid>0fd8ba6f-0923-4522-a9e8-7d5a873b9222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data tidak boleh kosong'])[4]/following::select[1]</value>
      <webElementGuid>6b0aa638-6b96-4a65-b3e0-7aba4114d636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data tidak boleh kosong'])[5]/preceding::select[1]</value>
      <webElementGuid>f0a72d75-e559-43a3-bef8-72d6da067368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan tempat lahir'])[1]/preceding::select[1]</value>
      <webElementGuid>3f08410c-6a33-4b04-a623-d6464d92c809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b3f8e569-6f2f-40b2-a9f4-0164115918f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' Jenis Kelamin  Laki-laki  Perempuan ' or . = ' Jenis Kelamin  Laki-laki  Perempuan ')]</value>
      <webElementGuid>9ba9c72f-2334-49f2-ad19-619b3ab2fb08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
