<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Foto Selfie dengan KTP</name>
   <tag></tag>
   <elementGuidId>6a0bd841-a3c7-474a-9530-59109e5ae797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[text()='Foto Selfie dengan KTP']/following-sibling::input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d017044d-3afb-447c-b0e3-486f123f59b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8ffe6645-3b9a-450e-b457-5ca6941c146b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>30b743da-896e-460c-8457-0b5cdafe0358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png,.jpg,.jpeg,.heif</value>
      <webElementGuid>c46a0dfd-3f1c-4268-ae6f-c3a250d17fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-0&quot;)/div[@class=&quot;d-flex&quot;]/div[1]/form[@class=&quot;form-edit ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;right-form&quot;]/div[@class=&quot;mb-24&quot;]/input[@id=&quot;file&quot;]</value>
      <webElementGuid>673e2df6-af67-4f0d-a4dd-2890be483da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='file'])[4]</value>
      <webElementGuid>72c3a882-77b5-465a-a76b-f7a8a95f43e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-0']/div[2]/div/form/div[2]/div[2]/input</value>
      <webElementGuid>91901c7c-29e6-422c-b036-416250b67567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>219290a4-c41c-41ba-ab88-867852299366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file']</value>
      <webElementGuid>dee362ab-ac6f-43c8-b505-5f600cdbeaed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
