<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Foto KTP</name>
   <tag></tag>
   <elementGuidId>89786f73-ed0d-40c0-8888-deffb43d159e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.right-form > div.mb-24 > #file</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[text()='Foto KTP']/following-sibling::input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65a5d536-7363-4a65-b449-9dc9d3ed7ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>91aa47d7-572a-446d-bf45-37ffd1a3328d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>52bf100d-dcba-4782-80c4-d8b3ba63b4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png,.jpg,.jpeg,.heif</value>
      <webElementGuid>af2c147f-c7e3-471c-b0ca-d62fe601d7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-0&quot;)/div[@class=&quot;d-flex&quot;]/div[1]/form[@class=&quot;form-edit ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;right-form&quot;]/div[@class=&quot;mb-24&quot;]/input[@id=&quot;file&quot;]</value>
      <webElementGuid>6752e761-10cc-4db4-a3af-e8ff234945d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='file'])[3]</value>
      <webElementGuid>4234bdd6-4a8d-484b-997e-ae2eae5e8b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-0']/div[2]/div/form/div[2]/div/input</value>
      <webElementGuid>ebcea548-7e07-437e-9fc3-ff03691a98e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fae4ef93-3ca5-432f-9b66-5d2e52a04212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file']</value>
      <webElementGuid>22ce64bd-5900-4d03-9fd1-207ee2250415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
