<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option - Pendidikan Terakhir</name>
   <tag></tag>
   <elementGuidId>199d1a63-de5b-4515-975d-86876acd141f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lancar-input//input[@formcontrolname='latest_education']/ancestor::lancar-input/following-sibling::lancar-dropdown-list/ul/li[text()=' ${pendidikan_terakhir} ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-4 > span.mat-option-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6e5305e-8f48-41c8-87b9-3eb3457ef376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>5237fee7-c919-4882-9439-6fe80ce2aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-4&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>879fc2f5-3d6f-456d-b7d5-5c38d0406515</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-4']/span</value>
      <webElementGuid>a39c41c1-b4d6-46bb-9d1a-42b53b5e42d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/following::span[1]</value>
      <webElementGuid>39f2ce0c-f90f-4a69-938c-ea04a134ac59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[2]</value>
      <webElementGuid>71541943-3a26-42e7-aca2-5c521bd4dd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submitted'])[1]/preceding::span[1]</value>
      <webElementGuid>59832724-2f0e-4d3e-b418-2cfd70b241cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[1]/preceding::span[2]</value>
      <webElementGuid>e12ad393-f376-4fda-9224-a0c7669e65fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passed']/parent::*</value>
      <webElementGuid>96181a18-9960-4ca9-84ba-53a9eb5bfb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>e0cff8d5-5980-4415-bde1-9520f181b30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Passed ' or . = ' Passed ')]</value>
      <webElementGuid>b86f75ad-63aa-4516-9bb5-e840b32ed438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
