<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NoHP - Agent</name>
   <tag></tag>
   <elementGuidId>80ab3976-8ad0-464e-a715-a0494f927689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content-right > h6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//app-scroll/team-list/ul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/ng-component/ul/li/div[2]/div[2]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-scroll/team-list/ul</value>
      <webElementGuid>769e0fbe-a044-4963-aeeb-362709850d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/ng-component/ul/li/div[2]/div[2]/h6</value>
      <webElementGuid>528eb0e9-8028-4151-b187-618ba9280d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor HP'])[1]/following::h6[1]</value>
      <webElementGuid>577fea2d-1064-4685-804c-aa07bf06aaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Bergabung'])[1]/following::h6[2]</value>
      <webElementGuid>5a8671ea-e15c-45b9-9e85-df994be252a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bambang'])[2]/preceding::h6[1]</value>
      <webElementGuid>2578a7c6-5bbb-41e1-bf56-02c9c25bd1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Bergabung'])[2]/preceding::h6[1]</value>
      <webElementGuid>54aef9af-cc2a-439b-b356-8eebf02e59d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20221005111854']/parent::*</value>
      <webElementGuid>6045be4c-ee83-4494-a03f-f02505ba7141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h6</value>
      <webElementGuid>a685ab0b-3132-4e98-baee-ddf9f9b32439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = '20221005111854' or . = '20221005111854')]</value>
      <webElementGuid>96be3218-cc75-45a0-afff-93e817181f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
