<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite Sales - Request List</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>01dd42f8-fa09-460e-8df7-93924e4b44a1</testSuiteGuid>
   <testCaseLink>
      <guid>6438fd9f-254e-45cc-b51e-6e6a00558795</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Login/Login with valid credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0b5bdd64-60b6-42b1-a442-0d85d4083b98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Navigation/Click menu Sales</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4705a2b3-5fc4-473d-b65b-71f7427f2cbd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Navigation/Click menu Request</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c29da52e-fe52-4c20-852e-503221f77da5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Nama</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a9585b7-cbca-4474-8d43-11c33456f286</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfa1a038-32a6-4585-a078-89d073fa0911</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by No HP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a71e51f-cf9e-4857-88f8-b66e8f5898d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>071ad250-951d-4666-a8c3-6cbce32e11c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Kategori Agen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd69e2c3-378e-49a8-ab21-34124e7af446</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2766ec73-3ebc-4d7c-bbd4-e13e27d9c23c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Kota Cabang</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88e34c42-b749-40f0-93cf-cfaf2b497231</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>083357c4-2614-47fa-ac2f-c3d0052a6c0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Nama Cabang</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50993baa-4801-4aae-b215-77ad91e6cdc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bbf9883-aaf2-40d6-bfc0-c7b1290a0e88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c42a3ad5-02aa-421b-acd2-5ea856328e96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Posisi</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e82bbc95-421b-4c3f-9803-32128975ea5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eae46aa-39b1-4fa5-bd09-6fd697c69aeb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Tipe Partner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee1811e8-d9df-456f-a4e0-5357f50045fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c28566ad-fea7-4140-98a2-21d3e49ae0df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Nama Partner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19be6573-a64c-4bab-8d9e-f891a0685d24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14a313e9-480d-4feb-a599-e990f549f48c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70f2d6aa-9701-4688-94f9-4b6f869207a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Cabang Partner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>118dcf34-02c4-4286-8524-63d39df4cbaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d26eaae-ebb3-4923-95b1-38532d93ac13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8eb8297-5a19-4dd2-ae1d-ea6dcd4ce742</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Filter list by Status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8319bb9-66eb-43c7-af1e-d6deb628f447</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31e4781a-2dcc-4a1e-a43d-112b33071001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Request/Open agent detail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>32d3e90a-8b4a-4ae2-ac13-3a29dea04fe7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Agent Detail/Deactivate agent</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6ba25c14-1dd0-44f2-a4d8-0dbb2a2c357e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Backoffice/Sales/Agent Detail/Edit Informasi Agent</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd08efab-dc16-4647-86d2-3b4f13ea6504</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>815c2798-3e5f-40bf-aa0c-597efda6de1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>776db851-d66b-4512-ab3e-d319db0881eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25867f75-7ad5-43b9-a9b0-7844370e7eb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c48cca88-6f3a-4f81-b296-f90f62eeff35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>631103a5-a177-4a39-b33e-110ae9f6036c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ff6697b-fbf0-4fef-b752-a8c773bf8d4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>171d51a4-9cf2-4bbd-a192-2602b5420f95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10baa649-9f3b-49a6-a0b4-cce94430c48a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eccb040-ef9a-4277-ae84-fbee385fead9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b224c7cb-4280-4bc8-884f-975814e095ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c503194-afbd-4fc5-8532-1e5c16cd001c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f564cd4d-dc8b-4223-997f-746d398bc9bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0084626d-cfd7-4dfc-a1a9-a8e6f0014773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd7eaa1c-ec0b-491a-88cf-0c4641f1b031</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0551e632-253d-4b33-bfe5-a2332960972b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1daeb04c-019d-4b30-aff3-04ae4ddf0899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e508510b-5258-4cbe-b78a-535a73342988</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39826476-e4a0-41eb-8c5e-064f204179a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ece6416d-c7b2-48c6-8d66-e5d2bd7e460c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f42de359-350e-4e21-a950-ca999fad9f7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>073d3f58-4155-41ba-83eb-00ca6d486956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92fe3068-5703-4ca4-9fa1-ff0343825347</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a43b085-f59c-4d97-a9c5-425af6419961</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bfb6c11-c38a-4f3d-bd81-c56fdf37037a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>021ff2f1-63a4-4c7a-86b0-ef0677780324</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8be4470-9943-4862-a8bb-f2df76aadb89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc43e1ae-4f53-4707-b950-660bf18852ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ffc7575-2079-47a0-8c78-4b070c568a42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b32cddb-bfd2-4d9f-9b77-934e9903ec76</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
