<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Tipe Pinjaman</name>
   <tag></tag>
   <elementGuidId>108cd710-81fc-4bb4-974a-b209c9de8ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'loanType']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-25']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e81f3a93-1a5c-4f88-be4f-626a1f50a7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c114-34</value>
      <webElementGuid>23dff043-2cb6-4b1e-b31a-f6173d45c50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-25</value>
      <webElementGuid>e5ac9694-a142-41da-8eed-f5dd58b7c244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LancarDana Bisnis</value>
      <webElementGuid>d3b42f71-0159-4b55-949e-ff8980408dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-25&quot;)</value>
      <webElementGuid>be2902c8-9ead-4564-9716-5071b4849f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>loanType</value>
      <webElementGuid>114ba87e-b411-4fda-8990-5ab2ebd94cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-25']</value>
      <webElementGuid>e15ca295-1ba9-471c-8234-aa7589430f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-24']/div/div</value>
      <webElementGuid>0015ab3b-7d9f-405d-9a4d-62ecf0492563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Pinjaman :'])[1]/following::div[6]</value>
      <webElementGuid>c7703411-65d1-46f1-a112-8fdff3bcca7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Pinjaman'])[1]/following::div[9]</value>
      <webElementGuid>7a2e7288-c840-4cd3-88f6-2a2000b709fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose One'])[1]/preceding::div[3]</value>
      <webElementGuid>f5e6603c-8707-4bd2-9ea5-4d3914b405d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div</value>
      <webElementGuid>45559450-ebde-4a1e-b208-2358ec9162a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-25' and (text() = 'LancarDana Bisnis' or . = 'LancarDana Bisnis')]</value>
      <webElementGuid>64b72c48-6272-4ec8-acfb-33733a716691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
