<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Masa Tenggang Pinalti Lender</name>
   <tag></tag>
   <elementGuidId>91c80445-85f2-44e5-adfd-7ad3dddeff9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-27']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-27</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdcaa540-bc97-4220-b539-8bb207346131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>lenderPenaltyGracePeriode</value>
      <webElementGuid>76a3e1ce-0e39-467e-8da5-7eb24e70bbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-untouched ng-pristine cdk-text-field-autofill-monitored ng-valid</value>
      <webElementGuid>90562334-6241-4ba1-a50b-58c720c85777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-27</value>
      <webElementGuid>97b0dab5-11f3-4800-9534-a45a5a2847a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f804724-062f-4d73-b15f-1d94b3eadefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a4faaee8-2129-40d6-b4b6-bc1045397572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-27&quot;)</value>
      <webElementGuid>195dfec7-e87d-4824-8716-af19fe921ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-27']</value>
      <webElementGuid>72f9282a-eb52-4b7d-a9e1-877b785b2b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/mat-form-field/div/div/div[2]/div/input</value>
      <webElementGuid>0f980554-8965-4116-8540-85361c52df96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-27']</value>
      <webElementGuid>fafb4e7f-be53-4afc-ba96-c414ea5f3d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
