<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Collateral NJOP</name>
   <tag></tag>
   <elementGuidId>b6176dcf-6f56-4a52-9a3f-527ff7f1e45f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0f4f56a-9a82-4861-88a0-e65473e3c114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>collateralNjopValue</value>
      <webElementGuid>6a0eb5f5-1afb-479b-adb0-008ca2bdc262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-untouched ng-pristine cdk-text-field-autofill-monitored ng-valid</value>
      <webElementGuid>b716781a-63dd-4e0d-a988-525ea05395cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-24</value>
      <webElementGuid>07ea1dc0-0c0c-4f97-a868-33ec4e8f6b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2097437a-f4a5-4826-a04f-8d0cd44f8fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de435af0-51ed-43d5-8d5f-6adf21f70765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-24&quot;)</value>
      <webElementGuid>a6f5e1db-bd62-4bdd-b07e-d625fdae55f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-24']</value>
      <webElementGuid>833f7e91-3c35-463c-a7ea-11281a942a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[37]/div/mat-form-field/div/div/div[2]/div/input</value>
      <webElementGuid>0fcbc73d-aca3-4307-8107-65eeb6057ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-24']</value>
      <webElementGuid>e3aa1dd3-499f-49f4-9f16-4b6af0722353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
