<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input - Biaya Admin</name>
   <tag></tag>
   <elementGuidId>b7529aa1-fbf7-4580-8877-e9dca1c01ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c55c42a9-1849-4687-939d-bb946ad2c95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>adminFee</value>
      <webElementGuid>7f6fbf04-d5dd-43d1-8957-b1baaa3eec33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-untouched ng-pristine cdk-text-field-autofill-monitored ng-valid</value>
      <webElementGuid>f4c3560c-85dc-4fc3-8a16-5081d640dacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-17</value>
      <webElementGuid>fc795fc4-cd8c-4d5d-add0-1a8a7d98b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9c30a33d-a4c3-4de0-91a6-7e5b234f79d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06ea18cd-d263-4897-b4d2-ebe055a30114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-17&quot;)</value>
      <webElementGuid>3b1a322d-a8ce-4f19-b257-e535b9a867d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-17']</value>
      <webElementGuid>c8086b78-c5d3-4d00-8606-4a546f2562c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/mat-form-field/div/div/div[2]/div/input</value>
      <webElementGuid>4b40aa4a-133c-4c37-8caf-867f4570d7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-17']</value>
      <webElementGuid>9a8f5beb-e26e-401e-9e07-52d8d3309b4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
