<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label - Konfirmasi</name>
   <tag></tag>
   <elementGuidId>f2a2a73a-3465-4a24-a8d9-8eb7e4d0729f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='mat-dialog-title-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-title-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>fd005e0d-709b-4fd4-a3a6-67a899d12980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-title</value>
      <webElementGuid>704f52f5-8193-4e78-bdeb-f811d525ef43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-title-3</value>
      <webElementGuid>30b9bbc8-7bb8-4384-8e4e-82ee08ffd975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Konfirmasi </value>
      <webElementGuid>9f065af1-92f7-4f12-99d4-cfb98e4b5bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-title-3&quot;)</value>
      <webElementGuid>4054a822-5289-461a-9e93-6826a53b41cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='mat-dialog-title-3']</value>
      <webElementGuid>7c19bd16-9ef1-469b-8d1a-4918d64c95d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-3']/app-warning-confirmation/app-dialog-header/div/h2</value>
      <webElementGuid>cb776db5-ef64-48f9-be70-a0cfcf82f8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-dialog-title-3', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>e0a695e9-7798-494e-b01a-34efeeda611d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h2[1]</value>
      <webElementGuid>071f130d-33cd-4ff8-9825-f2b6eaddfd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah anda yakin akan mengganti Loan Type?'])[1]/preceding::h2[1]</value>
      <webElementGuid>96b79356-4d12-4557-9297-b4d5e9fe1462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::h2[1]</value>
      <webElementGuid>2f69f7ae-26a4-4b99-93f0-541e560c9ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konfirmasi']/parent::*</value>
      <webElementGuid>3a8a94e3-5152-47f9-9d02-b6c8f10836f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c03c69e8-af29-437c-b3d4-4997fe8799f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'mat-dialog-title-3' and (text() = ' Konfirmasi ' or . = ' Konfirmasi ')]</value>
      <webElementGuid>42e12f69-3ab4-41aa-a66b-45207c51a76d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
