<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite Register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3b82b0f4-cd3f-44fd-928d-27ee112ced28</testSuiteGuid>
   <testCaseLink>
      <guid>757c6d9b-7089-4238-a39f-81bf67dfbee3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User using existing NIK</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf15b6da-20d5-4c2e-a990-4331b6f0807f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2869bd93-6f2f-49d4-9350-bb1b8c996d28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af210669-24e1-4f9d-90ac-9231442dcc98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6eda9e1-4df5-4fc0-bb8c-109a58c41b58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>365aa1f4-c04d-4e7e-8e3a-e5bc0bab20f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>697c1a30-0d6d-4cf2-af68-9438d4b35fb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>862f09b6-a723-4fa6-942a-d47aa5f035b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b083cff-279b-44eb-9e6f-dbcaad6b79eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d37a18db-5d6e-423a-9b55-d9b496b96192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06ff2ce4-1d0a-417c-963f-e031c29b6fbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32444906-81a1-4997-bde7-00424832439d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b12fa2a7-1687-4585-8a32-66907dd4e23a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c68de292-cb41-49a6-9249-27ec93b406df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9075f87-b3c7-46d5-9417-82aac878b1dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User AS Internal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a35aa6f-c46c-42cb-9d68-a9d9e5104387</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>161cce7e-1faa-4eb1-aea8-b0af0bf52700</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dbf0337-2f8a-40a6-84fb-e06f964f8031</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7a47d57-a439-409f-beeb-002c8600099b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User AS External Freelancer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cce5b95-fb35-4d62-9aa9-8188b52186c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0ba51b5-f51a-41d4-a700-0c56c123c6ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User AS External Freelance Head Office</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>388034c5-57a7-4727-95ad-37c1e716236a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c928dd0-d9a9-417a-b8c6-42b9d45444e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32680909-1bcc-4b00-800a-c81bb4278621</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93fd41d5-71ee-4d0c-bffd-e6bd01558007</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User AS External (not Freelancer)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c8a535d-91c2-4240-a62b-f5c16f8dadc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef821d5d-bfd8-4914-91ff-cb84de13fe56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b44c0309-8756-4d76-8f00-a4304c9e6664</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f46aeb75-5d18-41aa-b382-ad8c8e9718e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User AS Branch - Relationship Manager</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>069a7c83-24b1-4aeb-9e2b-869c2fefd865</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77f7c610-8629-4e94-a7dd-999df151006d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FE/Partner/Register/Register User AS Branch - Branch Manager</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>332bd39f-b164-496b-9174-f066b9767a7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bfe91bf-d7fe-4644-b2e7-2317cede2846</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
