<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextValue - Status</name>
   <tag></tag>
   <elementGuidId>fb42a1fb-6956-4da2-807e-b3079b36d697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-disbursement//tr[2]/td[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>abf40048-92ec-40e5-b75c-b7840fe16605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1661066407545</value>
      <webElementGuid>b442fd10-ce50-4d39-b38d-7899120920ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
