<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextValue - No Telepon</name>
   <tag></tag>
   <elementGuidId>bca6851f-ebf3-4149-95d3-5a3b2c75f817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-10']/div/app-loan-origin-rm-agen/ul/li[4]/app-label-text/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18ed19e5-f406-476a-b791-0e4f1643fbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-text</value>
      <webElementGuid>365a224f-9ff2-4018-970e-497f15afbb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> +6281241585514 </value>
      <webElementGuid>e68e9c73-1abd-451d-a2af-4c439c7581d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-10&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c89-28 ng-trigger ng-trigger-translateTab&quot;]/app-loan-origin-rm-agen[@class=&quot;ng-star-inserted&quot;]/ul[1]/li[@class=&quot;ng-star-inserted&quot;]/app-label-text[1]/div[@class=&quot;card-item&quot;]/div[@class=&quot;card-text&quot;]</value>
      <webElementGuid>c7d4d9fb-f64b-4260-b31f-7c29d61cd650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-10']/div/app-loan-origin-rm-agen/ul/li[4]/app-label-text/div/div</value>
      <webElementGuid>704675d6-3a72-4a01-aef3-f41b30014882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/following::div[1]</value>
      <webElementGuid>e1b9257e-b027-442c-90f4-dbb739638e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='titus.sutio@sentuh.dev'])[1]/following::div[2]</value>
      <webElementGuid>cc086283-67cc-466f-8857-1422a8e7a11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Agen'])[1]/preceding::div[1]</value>
      <webElementGuid>599e5479-ab26-4da7-b4b8-8efac285481d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch'])[1]/preceding::div[1]</value>
      <webElementGuid>54b7d35b-7f33-4303-950c-f57e3b6941ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+6281241585514']/parent::*</value>
      <webElementGuid>4037aaa5-aa0d-4071-b26b-1c25c788dbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/app-label-text/div/div</value>
      <webElementGuid>7f18d8b7-f553-4933-a818-da1d2f3195c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' +6281241585514 ' or . = ' +6281241585514 ')]</value>
      <webElementGuid>589794f5-5d7b-4a95-88e7-e7f7b9ca1e06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
