<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah5</name>
   <tag></tag>
   <elementGuidId>cdca8762-3651-4ca6-a3e3-f22b8ba0f056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[contains(@accept,&quot;.png,.jpg,.jpeg,.heif,.heic,.pdf&quot;)])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-light.btn-md</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button [contains (text(), 'Unggah File')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[contains(@accept,&quot;.png,.jpg,.jpeg,.heif,.heic,.pdf&quot;)])[1]</value>
      <webElementGuid>de050bcb-a38b-458c-b6a5-30a271d67360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a617ddce-75c6-4756-a505-5510d80d31a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto selfie dengan KTP'])[2]/following::button[1]</value>
      <webElementGuid>56ce5cae-8bfe-477d-a015-7015a19b0e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/following::button[1]</value>
      <webElementGuid>19cee6b1-1d1f-4af6-8d4c-9873d6cbb52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Unggah File']/parent::*</value>
      <webElementGuid>f05e3527-582f-4c9b-bd37-4ea295a51e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/app-button/button</value>
      <webElementGuid>a189190c-4703-4314-9f9f-b1baa78d1bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Unggah File ' or . = ' Unggah File ')]</value>
      <webElementGuid>d25ccd89-208b-43f4-a2e3-277228a90896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
