<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unggah_Foto tempat tinggal saat ini</name>
   <tag></tag>
   <elementGuidId>9c0f1899-279c-46a3-b8be-934c46ae2541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Foto tempat tinggal saat ini ' or . = ' Foto tempat tinggal saat ini ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/ng-component/form/app-form-group[3]/div/div/app-upload-document/div/ul/app-upload-document-item/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.upload-document-item.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>32530424-1dbf-499d-9848-4a197c9e3e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-document-item ng-star-inserted</value>
      <webElementGuid>08a8e9a4-a9a9-47b8-b053-06c30977371b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>resedential</value>
      <webElementGuid>a053644d-165a-4e32-853b-50fa56e25d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Foto tempat tinggal saat ini </value>
      <webElementGuid>f56333a6-dea2-43cd-980d-d12a46ec9f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/app-form-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-group row mb-4&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/app-upload-document[1]/div[@class=&quot;upload-document&quot;]/ul[@class=&quot;upload-document-list&quot;]/app-upload-document-item[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/li[@class=&quot;upload-document-item ng-star-inserted&quot;]</value>
      <webElementGuid>3f0fddee-6206-46fe-b1ec-6a5561bc2423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/ng-component/form/app-form-group[3]/div/div/app-upload-document/div/ul/app-upload-document-item/li</value>
      <webElementGuid>f44c2c90-ffaf-47c7-a523-9d3dc6f01203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah Foto Tempat Tinggal'])[1]/following::li[1]</value>
      <webElementGuid>ea0ceff3-0d31-4070-b838-809768345f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Pos'])[1]/following::li[1]</value>
      <webElementGuid>9924bd8d-2914-416c-bb31-b14c65ddc495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat domisili tidak sama dengan KTP'])[1]/preceding::li[1]</value>
      <webElementGuid>00b2216d-1c23-4bbe-9d38-49e73f933804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>e08f4f21-1bbf-4f2b-9060-624f4f5b059d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' Foto tempat tinggal saat ini ' or . = ' Foto tempat tinggal saat ini ')]</value>
      <webElementGuid>64df3312-c113-40fe-82b1-ad5c7e71abb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
