<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextValue - No Pinjaman</name>
   <tag></tag>
   <elementGuidId>6bfe4bfc-ba80-4b33-8c8e-8a5648a47379</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Debby Anggraini'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//app-loan-detail-table//tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fef505e2-9c54-4cd0-8475-a2f45264dbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-text</value>
      <webElementGuid>edd193e1-7c7c-440d-a0c5-d697c50bf567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>e6c7347c-2d17-4caa-acea-a86e253f373c</value>
      <webElementGuid>fa6c9080-9c52-439d-bc95-8e2fd2ae1504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-loan-detail-table//tr[1]/td[1]</value>
      <webElementGuid>aeebbc8a-19ce-4b4e-a61a-4da40b657921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debby Anggraini'])[1]/following::li[1]</value>
      <webElementGuid>20408113-a53b-479e-bf4e-ee8ef26e8c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::li[2]</value>
      <webElementGuid>92e8f7fa-9f7d-4748-91de-32f7c2c868a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::li[1]</value>
      <webElementGuid>1207ffdc-fc50-4b38-8bf8-44c32a838c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perempuan, 32 Tahun'])[1]/preceding::li[2]</value>
      <webElementGuid>41bfed66-31c4-4312-bdb8-92c1407075ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='e6c7347c-2d17-4caa-acea-a86e253f373c']/parent::*</value>
      <webElementGuid>b3a39f75-4987-41a5-84f9-da576663adac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>3cdbd65d-ec62-4c5a-aa71-fbd3d7b84537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'e6c7347c-2d17-4caa-acea-a86e253f373c' or . = 'e6c7347c-2d17-4caa-acea-a86e253f373c')]</value>
      <webElementGuid>5803fb42-3464-4625-9a03-e5339bf48aca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
