<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_daftar_pengajuan</name>
   <tag></tag>
   <elementGuidId>575298a0-e228-4579-8696-9d6ddce8b13a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.my-3.max-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/ng-component/div[2]/app-tab/div/div[2]/app-tab-item/div/app-list-loan/app-list-loan-item/div/div[2]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>61494e78-f3ae-4358-ada2-89ecc4e7c14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-3 max-line</value>
      <webElementGuid>e43dd300-6e53-4f56-a202-c10243003251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>adasdsad</value>
      <webElementGuid>589d0478-0164-48a2-a12f-921271aa8c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ng-trigger ng-trigger-routerAnimation&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mb-5&quot;]/app-tab[1]/div[@class=&quot;tab&quot;]/div[@class=&quot;tab-body&quot;]/app-tab-item[@class=&quot;ng-tns-c88-5 ng-star-inserted&quot;]/div[@class=&quot;tab-item ng-tns-c88-5 ng-trigger ng-trigger-slider ng-star-inserted&quot;]/app-list-loan[@class=&quot;ng-tns-c94-7 ng-tns-c88-5 ng-star-inserted&quot;]/app-list-loan-item[@class=&quot;ng-tns-c94-7 ng-star-inserted&quot;]/div[@class=&quot;application-card&quot;]/div[@class=&quot;application-card-body&quot;]/h5[@class=&quot;my-3 max-line&quot;]</value>
      <webElementGuid>5cd57065-0dc1-4cfe-b140-3e15d83ba1e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/ng-component/div[2]/app-tab/div/div[2]/app-tab-item/div/app-list-loan/app-list-loan-item/div/div[2]/h5</value>
      <webElementGuid>c66f252c-e4d0-4733-bd74-0ef3972cabf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelled'])[1]/following::h5[1]</value>
      <webElementGuid>58c515b7-ee6f-4c72-999b-9fff1f988bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tersimpan'])[1]/following::h5[1]</value>
      <webElementGuid>b3440cfd-ca54-4d00-a254-cc098bff8689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Pinjaman'])[1]/preceding::h5[1]</value>
      <webElementGuid>c2fd317b-c5a4-4301-9c48-dd5617b73c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp1,231,211,111'])[1]/preceding::h5[1]</value>
      <webElementGuid>a1f68c17-d3a7-4f93-94bc-fcc73bf12290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='adasdsad']/parent::*</value>
      <webElementGuid>e142dcd6-e2f3-4051-b4e6-e76ef10b616a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>c3b1280d-92ea-4dcf-8c69-84792bd9ddb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'adasdsad' or . = 'adasdsad')]</value>
      <webElementGuid>1cfab503-0f88-41be-a636-94fa58018856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
