<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ubah</name>
   <tag></tag>
   <elementGuidId>ad793398-8c0a-482d-8eed-9c3ca50dbd7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.my-3.max-line</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = ' Ubah ' or . = ' Ubah ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/ng-component/div[2]/app-tab/div/div[2]/app-tab-item/div/app-list-loan/app-list-loan-item/div/div[2]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d1fd905-0b7f-4b4d-badc-fe09cc7c498f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-3 max-line</value>
      <webElementGuid>f6c79ddd-b2b3-4b3e-8f6c-f52ec9cdc459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Ubah </value>
      <webElementGuid>156c322c-25c5-440a-bfcb-07629b2697c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;ng-trigger ng-trigger-routerAnimation&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mb-5&quot;]/app-tab[1]/div[@class=&quot;tab&quot;]/div[@class=&quot;tab-body&quot;]/app-tab-item[@class=&quot;ng-tns-c88-5 ng-star-inserted&quot;]/div[@class=&quot;tab-item ng-tns-c88-5 ng-trigger ng-trigger-slider ng-star-inserted&quot;]/app-list-loan[@class=&quot;ng-tns-c94-7 ng-tns-c88-5 ng-star-inserted&quot;]/app-list-loan-item[@class=&quot;ng-tns-c94-7 ng-star-inserted&quot;]/div[@class=&quot;application-card&quot;]/div[@class=&quot;application-card-body&quot;]/h5[@class=&quot;my-3 max-line&quot;]</value>
      <webElementGuid>e1d4dd51-d4ff-4b0c-9589-769facafba68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/ng-component/div[2]/app-tab/div/div[2]/app-tab-item/div/app-list-loan/app-list-loan-item/div/div[2]/h5</value>
      <webElementGuid>661f6fdd-c7c0-424f-ab52-d185978a47e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelled'])[1]/following::h5[1]</value>
      <webElementGuid>f4af7a0c-b855-4a79-b57d-77430591df67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tersimpan'])[1]/following::h5[1]</value>
      <webElementGuid>c441db1f-7945-4496-9a43-f2a898484c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Pinjaman'])[1]/preceding::h5[1]</value>
      <webElementGuid>9752d307-5ee2-433a-8e4a-9c669c41b2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp1,231,211,111'])[1]/preceding::h5[1]</value>
      <webElementGuid>ebe54f55-5bf2-4bbd-b95d-01f20f5821b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='adasdsad']/parent::*</value>
      <webElementGuid>de084037-e9ca-49e7-92e8-f712da4f909d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>4ca4f0f1-34f2-4e98-b936-b85c09aac2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'adasdsad' or . = 'adasdsad')]</value>
      <webElementGuid>3def45a4-cf3a-4766-8495-7f481498f3cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
