<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox - Sertifikat Kepemilikan</name>
   <tag></tag>
   <elementGuidId>4919abb6-82f8-40ef-9d38-a38d9cfcd44d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-checkbox-inner-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-checkbox[@id='mat-checkbox-1']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>616d4f23-b176-4f44-af55-56147bea57f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-checkbox-inner-container</value>
      <webElementGuid>30522688-d65c-4e3f-a425-c756ac9872dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()=&quot;Kepemilikan (SHM/SHGB/SHMSRS)&quot;]/ancestor::label/span[1]</value>
      <webElementGuid>c5e08d26-4b17-450a-ae27-bffdb0b17301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-checkbox[@id='mat-checkbox-1']/label/span</value>
      <webElementGuid>ff070ef9-63ab-41b8-bcb8-7ea63f720729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apa jenis sertifikatnya?'])[1]/following::span[1]</value>
      <webElementGuid>6225497a-9ea8-46c7-a4ef-1968ee796a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::span[1]</value>
      <webElementGuid>b3f1286f-98f7-40a2-a688-b8c672d6969d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kepemilikan (SHM/SHGB/SHMSRS)'])[1]/preceding::span[7]</value>
      <webElementGuid>54982969-69de-41ce-915f-b6ff16c8d146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BPKB motor'])[1]/preceding::span[15]</value>
      <webElementGuid>16d6e88e-d772-4093-b1e0-41a6c2cf3e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-checkbox/label/span</value>
      <webElementGuid>950ac883-7025-4aaa-a43f-e4f9605bcf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
