<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioBtn - Tujuan Bisnis</name>
   <tag></tag>
   <elementGuidId>cf3f09ef-1107-4780-bce6-f5f97502bb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-3 > label.mat-radio-label > span.mat-radio-container > span.mat-radio-outer-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-3']/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35494ff8-2b74-48f7-b80b-d327210c6bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-outer-circle</value>
      <webElementGuid>138dafb0-c89d-485c-8d13-013c7d2aa3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()=&quot;Bisnis&quot;]/ancestor::label/span[1]</value>
      <webElementGuid>80a76ea8-4e01-4524-9bb3-1925a4eb5ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-3']/label/span/span</value>
      <webElementGuid>283e1cc8-985f-41c5-ad28-4038e2a51152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-radio-button[2]/label/span/span</value>
      <webElementGuid>ae24a728-e471-4e58-a9af-93c664c1ccd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
