<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioBtn - Agunan Tidak</name>
   <tag></tag>
   <elementGuidId>79d7b207-e9d7-4a6c-bd10-9c1eb57c8b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-radio-6 > label.mat-radio-label > span.mat-radio-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-6']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf414889-c15a-4313-bbd0-90d5994fc2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-container</value>
      <webElementGuid>ed245ec3-d1c4-4f1a-9852-7ef0aab7bbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()=&quot;Tidak&quot;]/ancestor::label/span[1]</value>
      <webElementGuid>a4374b22-a849-4697-b6bf-46213989c899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-6']/label/span</value>
      <webElementGuid>4f646a96-e2bb-4f4b-a1d8-334fd97d684e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[1]/following::span[1]</value>
      <webElementGuid>193224b9-2936-44eb-8d6f-2a75251391ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda di tempat yang tepat! Sekarang, apakah Anda memiliki sertifikat untuk diagunkan?'])[1]/following::span[8]</value>
      <webElementGuid>a00c3b6c-3f1e-4361-b293-133a0f1af255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/preceding::span[6]</value>
      <webElementGuid>d2b97bf0-11a5-4410-bd91-c3a778fa86b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lancar by Danamas |'])[1]/preceding::span[7]</value>
      <webElementGuid>02e30c6e-4655-4912-b3cc-cb410f9da550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/app-radio/div/mat-radio-group/mat-radio-button[2]/label/span</value>
      <webElementGuid>14089ad8-4e26-4409-92e4-22bf617d8c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
