<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Password Toggle</name>
   <tag></tag>
   <elementGuidId>68550436-3169-4788-a24d-e5fac0e85c7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.suffix.ng-tns-c58-4.ng-star-inserted > img.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed68e418-ea77-4809-99d0-b8614487d9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/icons/eye-show.svg</value>
      <webElementGuid>e0c73783-36a2-4e0a-b868-69a29ee40de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>36ba0de0-319f-4bdc-b653-34ea09176f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-form-field[@name=&quot;password&quot;]//img</value>
      <webElementGuid>614b39ae-e6fb-4570-b7c2-07d2bc370d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>7d0b494c-a75c-4b37-af50-b0992458e118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/icons/eye-show.svg']</value>
      <webElementGuid>df275b3f-2018-42a6-b794-9eccb066242e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
