<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text - Invalid Email Error</name>
   <tag></tag>
   <elementGuidId>5892f2ed-2eed-4f77-8d21-c1f677670256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-error-35</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-35']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>ed17741d-d054-4ea3-be01-a3d305075968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>6c79714a-7865-4910-870b-a467ba0d22c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error error-message ng-star-inserted</value>
      <webElementGuid>91e78b72-b5a2-4985-a3b0-3c18af372d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-35</value>
      <webElementGuid>a6a883b3-e842-455a-bfc6-70a1c1999c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Alamat email yang Anda masukkan tidak sesuai </value>
      <webElementGuid>50a5aa75-21f3-4a6b-9519-198a84efc3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-35&quot;)</value>
      <webElementGuid>6b6d87d1-42a8-4e0a-94ed-4928245e0459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-35']</value>
      <webElementGuid>5d3a3101-83b2-4a8b-912a-1e989ed33b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-11']/mat-error</value>
      <webElementGuid>13562762-e64a-4c3e-a032-4795f96c5746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Email'])[1]/following::mat-error[3]</value>
      <webElementGuid>fd579650-8c24-4f32-92cf-7ba773bbe67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/following::mat-error[3]</value>
      <webElementGuid>e18c64f7-c524-40ad-9198-ef1cba8719cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode referral (opsional)'])[1]/preceding::mat-error[7]</value>
      <webElementGuid>c165155e-2b2e-434b-aa3f-25add73904e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/preceding::mat-error[7]</value>
      <webElementGuid>2bd3867f-2fc5-4a3b-b4cc-e9ab5cd92a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alamat email yang Anda masukkan tidak sesuai']/parent::*</value>
      <webElementGuid>8d1064b9-34db-47bd-82bf-0d2ac2963077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error[2]/mat-error</value>
      <webElementGuid>6db73fc7-352a-434d-b434-48df55c2cd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-35' and (text() = ' Alamat email yang Anda masukkan tidak sesuai ' or . = ' Alamat email yang Anda masukkan tidak sesuai ')]</value>
      <webElementGuid>7d537ed7-0a64-4571-bf9a-67388bb3b5a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
