<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Ubah Informasi Pribadi</name>
   <tag></tag>
   <elementGuidId>dfc4397e-a3f1-4db9-916b-ae65da24a06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>72dbfb1e-5981-49ae-a449-377b3fd8a162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>5083e719-5eac-4a60-b548-5aa18a086f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah Informasi Pribadi</value>
      <webElementGuid>d4422624-89c5-4aaa-8046-425871f5858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/h2[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>7d8fd2cd-b7b7-4e80-aff0-a75155bf4cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/h2</value>
      <webElementGuid>f199e3c6-d2ec-407b-b461-0a15761c6393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lengkap'])[1]/preceding::h2[1]</value>
      <webElementGuid>b6ff00f1-0159-4f12-a161-5015401d7a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='muhammad yusuf'])[1]/preceding::h2[1]</value>
      <webElementGuid>d3e2861a-88b9-49f6-8211-9b7c34309e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>b6417bf6-6740-4b40-8e09-dce594bcdf3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Ubah Informasi Pribadi' or . = 'Ubah Informasi Pribadi')]</value>
      <webElementGuid>72fd91e7-58db-431b-987f-57ebff5bc148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
