<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_gender</name>
   <tag></tag>
   <elementGuidId>5d0d1790-242e-43e6-bc3e-d9fe4321638d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@auto_name=&quot;gender&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-select.app-drop-down-select.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ' or . = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>19f82168-41d1-43a6-ba11-f1e40ac4d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select app-drop-down-select ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>cef1bcbe-947a-4469-a943-aff262b7f5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>marital_status</value>
      <webElementGuid>ba3a3e48-3d13-4e1d-bf7a-52f60a20d90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati </value>
      <webElementGuid>33aee944-a2c1-4ed5-a635-4ba660be7c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/app-form-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-group row mb-4 required&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/app-select[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/select[@class=&quot;form-select app-drop-down-select ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]</value>
      <webElementGuid>3bded208-6ebd-4307-996d-ce49dc54b80c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/ng-component/form/app-form-group[11]/div/div/app-select/select</value>
      <webElementGuid>70792c37-1d0a-44d0-8fa3-7dda2c66f9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Perkawinan'])[1]/following::select[1]</value>
      <webElementGuid>ff403d30-e181-4a11-935c-c40f2253f67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data tidak boleh kosong'])[7]/following::select[1]</value>
      <webElementGuid>f8339f09-8a70-45ab-a338-21b7285ea934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>ca821625-80b9-4661-b18e-dd684ea2e1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-group[11]/div/div/app-select/select</value>
      <webElementGuid>243251f7-629a-40b6-93b8-f49a0f4539db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ' or . = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ')]</value>
      <webElementGuid>41d60373-6e50-4fcc-89c8-87b6992c5bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
