<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_detail pekerjaan</name>
   <tag></tag>
   <elementGuidId>8f092a5f-769a-4bf3-abe9-30c829b363d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-select.app-drop-down-select.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/ng-component/form/app-form-group[2]/div/div/app-select/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00214d27-1a76-4b35-8580-0d2d216bc254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select app-drop-down-select ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>ba6662c7-eb89-40ca-8bd6-d5c923df50ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>job_detail</value>
      <webElementGuid>06c27669-3b6e-40c7-8e45-d4bf05112309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih detail pekerjaan  Pegawai Negeri  Pegawai Swasta  Pegawai BUMN/BUMD  TNI/Polri  Pengusaha  Pedagang  Petani/Nelayan  Lain-lain </value>
      <webElementGuid>53bb7ad7-cf46-4806-9458-95973d4e01d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/app-form-group[2]/div[@class=&quot;form-group row mb-4 required&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/app-select[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/select[@class=&quot;form-select app-drop-down-select ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]</value>
      <webElementGuid>b9fe5e0a-071b-477f-8f63-3c426330e17b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/ng-component/form/app-form-group[2]/div/div/app-select/select</value>
      <webElementGuid>7ba193ef-6dbe-4e5e-80bd-dd44993fece8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Pekerjaan'])[1]/following::select[1]</value>
      <webElementGuid>10150aec-b309-4bb6-9cf6-f8c46fb8f909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data tidak boleh kosong'])[1]/following::select[1]</value>
      <webElementGuid>46fbd4a9-d12c-4616-902c-d37328971ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama Bekerja/Usaha'])[1]/preceding::select[1]</value>
      <webElementGuid>7e2e617e-5ef0-41ba-be53-e110774b5719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sumber Pendapatan'])[1]/preceding::select[2]</value>
      <webElementGuid>7d7476c5-58ed-4d50-9830-c3fdf37ffa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-group[2]/div/div/app-select/select</value>
      <webElementGuid>ea38ce24-7274-467f-9fc1-0b9f2f70099b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' Pilih detail pekerjaan  Pegawai Negeri  Pegawai Swasta  Pegawai BUMN/BUMD  TNI/Polri  Pengusaha  Pedagang  Petani/Nelayan  Lain-lain ' or . = ' Pilih detail pekerjaan  Pegawai Negeri  Pegawai Swasta  Pegawai BUMN/BUMD  TNI/Polri  Pengusaha  Pedagang  Petani/Nelayan  Lain-lain ')]</value>
      <webElementGuid>2f5d70c9-b4f9-40a0-a94d-ae3d7e513f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
