<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tipe peminjam</name>
   <tag></tag>
   <elementGuidId>e947f0be-42ce-42ec-a3ad-e3ad1106908a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/ng-component/form/app-form-group/div/div/app-select/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-select.app-drop-down-select.ng-untouched.ng-pristine.ng-valid.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>66cf75b5-d030-411c-bbd1-b3f258bffea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select app-drop-down-select ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>6e455092-9cc2-450c-b065-90f61a8af510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>borrower_type</value>
      <webElementGuid>de36313f-a5d2-4740-98bd-9ca6b97410ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih tipe peminjam  Individual </value>
      <webElementGuid>e7766c2c-ecd2-4f9f-ad41-45a5e75264dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/app-form-group[1]/div[@class=&quot;form-group row mb-4 required&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/app-select[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/select[@class=&quot;form-select app-drop-down-select ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]</value>
      <webElementGuid>c3205f1d-c94c-49d4-af76-81966c5410f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/ng-component/form/app-form-group/div/div/app-select/select</value>
      <webElementGuid>05e5b1d4-7fa1-4b8f-94f0-b437cf79ce4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Peminjam'])[1]/following::select[1]</value>
      <webElementGuid>6110725d-2f96-42cc-8694-bb07e19d725e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pinjaman'])[1]/following::select[1]</value>
      <webElementGuid>5c53aa84-2af6-4cf4-88be-3a45f4ff2c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan Pinjaman'])[1]/preceding::select[1]</value>
      <webElementGuid>0b83e804-ec96-4d12-8311-c6e01f51d167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Pinjaman'])[1]/preceding::select[2]</value>
      <webElementGuid>10aedd6b-8c85-4ff4-b8df-9cf840882ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d39f7658-0647-448b-8bbc-66a7de1d2508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' Pilih tipe peminjam  Individual ' or . = ' Pilih tipe peminjam  Individual ')]</value>
      <webElementGuid>dbed0b5a-bd88-4e42-a06e-52f5c1472057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
