<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Unggah Rekening Koran</name>
   <tag></tag>
   <elementGuidId>9a55783d-377e-463c-8bb7-40c5e155edf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='list']/ul/li/app-doc/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.rectangle-464-electric.desktop-disclaimer.pointer.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[text()=&quot;Rekening Koran (3 Bulan Terakhir)&quot;]/ancestor::app-doc//button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e359a28e-66a5-443c-85b6-9e0766fe3d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rectangle-464-electric desktop-disclaimer pointer ng-star-inserted</value>
      <webElementGuid>fbfa5381-ef6e-491c-9aa0-1d920a908e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>bb5bc0b6-9a9f-4eb9-8744-49d37f80213c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()=&quot;Rekening Koran (3 Bulan Terakhir)&quot;]/ancestor::app-doc//button/span</value>
      <webElementGuid>c5e78648-a083-4588-aea9-c2ea5c5b36a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='list']/ul/li/app-doc/div/button</value>
      <webElementGuid>7b3e6c09-0796-4a04-aabc-73650afc7bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Agunan'])[1]/following::button[1]</value>
      <webElementGuid>744e91c2-5c6e-47a5-b564-a924ea65a415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Finansial'])[1]/following::button[1]</value>
      <webElementGuid>478b4837-5700-4005-8f41-89a423a3c5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[2]/preceding::button[1]</value>
      <webElementGuid>7262e524-f375-4e31-a733-89339aa8c1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-doc/div/button</value>
      <webElementGuid>37ff8f39-cf2f-4e4c-8e29-091ab220e6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>61f4528d-a423-4676-bab6-070f97047538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
