<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Unggah Foto Agunan Dalam</name>
   <tag></tag>
   <elementGuidId>d11aa046-6b4a-48bc-889c-d9f1ee6b3533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='list']/ul/li[4]/app-doc/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ad9e56e-dc84-49b1-a21b-7cdf8c8a37e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rectangle-464-electric desktop-disclaimer pointer ng-star-inserted</value>
      <webElementGuid>82bdbe72-6578-492f-9b74-c833ea70789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>df84ab24-4a7d-48bb-90dc-289b1fcc0c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()=&quot;Foto Agunan Tampak Dalam&quot;]/ancestor::app-doc//button/span</value>
      <webElementGuid>bad1d5d0-fcd9-46e0-815d-a67efff04505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='list']/ul/li[4]/app-doc/div/button</value>
      <webElementGuid>a5478070-b587-411e-a3d3-781212e074b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[3]/following::button[1]</value>
      <webElementGuid>4db81ca2-a142-4682-ae4f-5646974ef5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[2]/following::button[2]</value>
      <webElementGuid>3bb7b4fb-1ecd-4049-9b34-fd7d89341bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[5]/preceding::button[1]</value>
      <webElementGuid>6fa988ec-9086-4151-ba26-b3ce3173858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/app-doc/div/button</value>
      <webElementGuid>d12ce28c-e014-480e-8e71-1ce9f653db48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>20910509-9d93-4850-89fc-6a5e2edf2175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
