<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextValue - Top file name (popup)</name>
   <tag></tag>
   <elementGuidId>7ca8e77e-93fe-4ca0-882f-8da04c71630a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/app-single-upload-dialog/div/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.underline</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-dialog-container//ul/li[1]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c606e4e8-6949-4a69-b1d3-c982421ba1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>14ee97fa-3bac-4994-8e38-0450db5b091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-dialog-container//ul/li[1]//span</value>
      <webElementGuid>360a91d5-e8a4-4073-89c7-15b9851868b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/app-single-upload-dialog/div/ul/li/a/span</value>
      <webElementGuid>dc7384d3-939a-4d93-aa64-50366da21fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[2]/following::span[3]</value>
      <webElementGuid>f63e778f-7bc7-47d7-ba00-606642d0f87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buku Nikah'])[2]/following::span[5]</value>
      <webElementGuid>32470cb1-7319-457e-bb45-de3b6f59f38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIMPAN'])[1]/preceding::span[1]</value>
      <webElementGuid>7a36fb11-3216-429c-b04f-b8c1f36484f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[1]</value>
      <webElementGuid>877594c6-cb0a-476e-9d4f-ac24031408b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>d3c4d712-e213-4e6f-900b-fc2ec0e1f38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Buku Nikah' or . = 'Buku Nikah')]</value>
      <webElementGuid>07f4fb70-02d5-4558-8be6-3cb5e4171d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
