<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option - Role</name>
   <tag></tag>
   <elementGuidId>ece0e986-c49f-4c50-8f7c-dbffbfb7fc9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/lancar-check-box/div/p[text()='${role}']/preceding-sibling::img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>555bcff3-ee68-491d-91bd-3d49d4c17cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1662436400217</value>
      <webElementGuid>cbd43075-2de0-4b6a-a9c2-59649e28d920</webElementGuid>
   </webElementProperties>
</WebElementEntity>
