<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button - Simpan</name>
   <tag></tag>
   <elementGuidId>b54d5730-e342-4d36-887a-61b08dfe383f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-edit-informasi-pekerjaan/footer//div[text()='Simpan']/parent::button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>325798bd-6b9f-472a-b4db-8d214fb57c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1661863908495</value>
      <webElementGuid>40adfca3-26e1-47e7-b68b-3126dff0eadc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
