<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_hubungan</name>
   <tag></tag>
   <elementGuidId>167181f7-cf89-4173-8335-315a8b655dda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@auto_name=&quot;relation&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ' or . = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-select.app-drop-down-select.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>87a6f6ac-5941-4f2f-aedf-f148cf4ae00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select app-drop-down-select ng-untouched ng-pristine ng-invalid ng-star-inserted</value>
      <webElementGuid>438a3b57-b7cb-45c0-bf57-f7ba648cc012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>auto_name</name>
      <type>Main</type>
      <value>marital_status</value>
      <webElementGuid>6e48c761-2e88-4ca3-b51a-3ca5b27ceced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati </value>
      <webElementGuid>cbd00b37-8804-4f6e-ad89-88de5b170fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-star-inserted ng-touched&quot;]/app-form-group[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-group row mb-4 required&quot;]/div[@class=&quot;font-weight-400 col-12&quot;]/app-select[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/select[@class=&quot;form-select app-drop-down-select ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]</value>
      <webElementGuid>bbf039ed-2276-407f-ae10-627910821b28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/ng-component/form/app-form-group[11]/div/div/app-select/select</value>
      <webElementGuid>4fd19b6b-97ff-420b-b4f1-9c56facbb455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Perkawinan'])[1]/following::select[1]</value>
      <webElementGuid>232cb0e6-8ad3-4af5-ad44-0b362df43244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data tidak boleh kosong'])[7]/following::select[1]</value>
      <webElementGuid>92be143d-8985-44fc-9c79-c796f3be940c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>200aa4f8-27f3-4221-95f6-40bcc5ff08ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-form-group[11]/div/div/app-select/select</value>
      <webElementGuid>47a00882-00bb-4794-b9dc-354f510074be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ' or . = ' Pilih status perkawinan  Belum kawin  Kawin  Cerai Hidup  Cerai Mati ')]</value>
      <webElementGuid>a35c841f-690e-4690-890b-b17c18213093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
